[build]
  command = "yarn build:with-prefix"
  functions = "/functions"
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' cdn.segment.io,www.google-analytics.com; style-src 'self' 'unsafe-inline' fonts.googleapis.com; img-src *; font-src 'self' fonts.gstatic.com; connect-src 'self' *.segment.io,www.google-analytics.com"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = ""
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
